# Generated by Django 3.2 on 2021-10-31 08:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('br_id', models.AutoField(primary_key=True, serialize=False)),
                ('br_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=100)),
                ('c_qp_code', models.CharField(max_length=6)),
                ('c_credits', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('cl_id', models.AutoField(primary_key=True, serialize=False)),
                ('sems', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default='1', max_length=2)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('reg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reg_value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=100)),
                ('std_dob', models.DateField(default=datetime.datetime(2021, 10, 31, 8, 0, 37, 120831, tzinfo=utc))),
                ('std_addr', models.TextField()),
                ('std_email', models.EmailField(max_length=254)),
                ('std_contact', models.CharField(max_length=20)),
                ('br_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.branch')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.department')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.regulation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('NA', 'Not Assign'), ('SA', 'Shortage of Attendance'), ('RA', 'ReAppear'), ('B', 'Above Average'), ('B+', 'Good'), ('A', 'Very Good'), ('A+', 'Excellent'), ('O', 'Outstanding')], default='NA', max_length=10)),
                ('external_marks', models.IntegerField()),
                ('internal_marks', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('att_1', models.IntegerField()),
                ('att_2', models.IntegerField()),
                ('att_3', models.IntegerField()),
                ('int_1', models.IntegerField()),
                ('int_2', models.IntegerField()),
                ('int_3', models.IntegerField()),
                ('cl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.courselist')),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
                ('f_desgination', models.CharField(choices=[('Teaching Follow', 'Teaching Follow'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor')], default='Teaching Follow', max_length=20)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='dep_hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.faculty'),
        ),
        migrations.AddField(
            model_name='courselist',
            name='f_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='dep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.department'),
        ),
        migrations.AddField(
            model_name='branch',
            name='dep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.department'),
        ),
    ]
